version: "3.9"

services:
  bullos-runner:
    image: ghcr.io/vikshrogit/bullos-gh-runner:latest
    container_name: ${RUNNER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GITHUB_URL=${GITHUB_URL}
      - GITHUB_PAT=${GITHUB_PAT:-""}
      - RUNNER_TOKEN=${RUNNER_TOKEN:-""}
      - RUNNER_NAME=${RUNNER_NAME:-${HOSTNAME}}
      - RUNNER_LABELS=${RUNNER_LABELS:-"self-hosted,Linux,X64"}
      - RUNNER_WORKDIR=${RUNNER_WORKDIR:-"_work"}
      - RUNNER_EPHEMERAL=${RUNNER_EPHEMERAL}
      - RUNNER_RUNNERGROUP=${RUNNER_RUNNERGROUP}
      - RUNNER_DEBUG=${RUNNER_DEBUG}
      - RUNNER_CONCURRENCY=${RUNNER_CONCURRENCY}
      - METRICS_ENABLED=${METRICS_ENABLED:-false}
      - TRACING_ENABLED=${TRACING_ENABLED:-false}
      - AUTOSCALE_MODE=${AUTOSCALE_MODE:-false}
    volumes:
      - bullos_runner_data:/${RUNNER_WORKDIR}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  bullos_runner_data:
    driver: local
