blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/vikshrogit/bullos-gh-runner#readme
    about: Read the project documentation
  - name: 💬 Discussions
    url: https://github.com/vikshrogit/bullos-gh-runner/discussions
    about: For questions, ideas, and general chat
  - name: 🔒 Security
    url: https://github.com/vikshrogit/bullos-gh-runner/security/policy
    about: Please report vulnerabilities via our security policy
